app_id: "073026d5-cc74-4247-a1a6-ab438a3314e2"
app_secret: "d1e80bd3-838c-4aae-984e-7c076b9d2b91"
redirect: "http://localhost:8000/landingpage"
scopes:
  - user.read
  - mailboxsettings.read
  - calendars.readwrite
authority: "https://login.microsoftonline.com/05f00303-5336-44d6-863e-165186fcbdef"